name: DaVinci CI/CD (Dev → Test → Prod)

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate DaVinci Bearer Token
        id: token
        run: |
          RESPONSE=$(curl -s -X POST \
            -u "${{ secrets.TEST_DAVINCI_CLIENT_ID }}:${{ secrets.TEST_DAVINCI_CLIENT_SECRET }}" \
            -H "Content-Type: application/x-www-form-urlencoded" \
            -d "grant_type=client_credentials" \
            "https://orchestrate-api.eu.${{ secrets.TEST_REGION }}.pingone.com/v1/environments/${{ secrets.TEST_ENV_ID }}/auth/token")

          TOKEN=$(echo $RESPONSE | jq -r '.access_token')
          echo "token=$TOKEN" >> $GITHUB_OUTPUT

      - name: Import DaVinci Flow
        run: |
          curl -s -X POST \
            -H "Authorization: Bearer ${{ steps.token.outputs.token }}" \
            -H "Content-Type: application/json" \
            --data @davinci/flows/*.json \
            "https://orchestrate-api.eu.${{ secrets.TEST_REGION }}.pingone.com/v1/environments/${{ secrets.TEST_ENV_ID }}/flows/import"

      - name: Publish DaVinci Flow
        run: |
          curl -s -X POST \
            -H "Authorization: Bearer ${{ steps.token.outputs.token }}" \
            "https://orchestrate-api.eu.${{ secrets.TEST_REGION }}.pingone.com/v1/environments/${{ secrets.TEST_ENV_ID }}/flows/publish"

  ##########################
  # 1. Deploy to TEST (manual approval)
  ##########################
  deploy-test:
    name: Deploy to Test
    runs-on: ubuntu-latest
    needs: deploy-dev
    environment:
      name: test
      url: https://apps.pingone.eu/9a773ab2-5392-467e-86bc-7bb683d1ae7f/myapps/  #application portal URL
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan TEST
        run: |
          terraform plan \
            -var "davinci_client_id=${{ secrets.TEST_DAVINCI_CLIENT_ID }}" \
            -var "davinci_client_secret=${{ secrets.TEST_DAVINCI_CLIENT_SECRET }}" \
            -var "davinci_environment_id=${{ secrets.TEST_DAVINCI_ENVIRONMENT_ID }}"

      - name: Terraform Apply TEST
        run: |
          terraform apply -auto-approve \
            -var "davinci_client_id=${{ secrets.TEST_DAVINCI_CLIENT_ID }}" \
            -var "davinci_client_secret=${{ secrets.TEST_DAVINCI_CLIENT_SECRET }}" \
            -var "davinci_environment_id=${{ secrets.TEST_DAVINCI_ENVIRONMENT_ID }}"
