name: DaVinci CI/CD (Dev → Test → Prod)

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:

 
  ##########################
  # 1. Deploy to TEST (manual approval)
  ##########################
  deploy-test:
    name: Deploy to Test
    runs-on: ubuntu-latest
    needs: deploy-dev
    environment:
      name: test
      url: https://apps.pingone.eu/9a773ab2-5392-467e-86bc-7bb683d1ae7f/myapps/  #application portal URL
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan TEST
        run: |
          terraform plan \
            -var "davinci_client_id=${{ secrets.TEST_DAVINCI_CLIENT_ID }}" \
            -var "davinci_client_secret=${{ secrets.TEST_DAVINCI_CLIENT_SECRET }}" \
            -var "davinci_environment_id=${{ secrets.TEST_DAVINCI_ENVIRONMENT_ID }}"

      - name: Terraform Apply TEST
        run: |
          terraform apply -auto-approve \
            -var "davinci_client_id=${{ secrets.TEST_DAVINCI_CLIENT_ID }}" \
            -var "davinci_client_secret=${{ secrets.TEST_DAVINCI_CLIENT_SECRET }}" \
            -var "davinci_environment_id=${{ secrets.TEST_DAVINCI_ENVIRONMENT_ID }}"
